#Automatically Runs Great Expectation Checkpoints on every push to a PR, and provides links to hosted Data Docs if there an error.
name: PR Push
on: pull_request

jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest
    steps:

      # Clone the contents of the repository
    - name: Copy Repository Contents
      uses: actions/checkout@main

      # Run Great Expectations and deploy Data Docs to Netlify
    - name: Run Great Expectation Checkpoints
      id: ge
      uses: superconductive/great_expectations_action@main
      continue-on-error: true
      with:
        CHECKPOINTS: "locations.rds.chk"
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_USER: ${{ secrets.DB_USER }} 
 
    - name: print env variables
      run: env
      env:
        URL: ${{ steps.ge.outputs.docs_url }}
        PASSED_CHECKPOINTS: ${{ steps.ge.outputs.passing_checkpoints }}
        FAILED_CHECKPOINTS: ${{ steps.ge.outputs.failing_checkpoints }}
 
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
      env:
        URL: ${{ steps.ge.outputs.docs_url }}
        PASSED_CHECKPOINTS: ${{ steps.ge.outputs.passing_checkpoints }}
        FAILED_CHECKPOINTS: ${{ steps.ge.outputs.failing_checkpoints }}
 
    # If a checkpoint failed, comment on the PR with a link to the Data Docs hosted on Netlify.
    - name: Comment on PR upon Checkpoint failure
      if: steps.ge.outputs.checkpoint_failure_flag == '1'
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Failed Great Expectations Checkpoint(s) \`${FAILED_CHECKPOINTS}\` detected for: ${process.env.GITHUB_SHA}.  Corresponding Data Docs have been generated and can be viewed [here](${process.env.URL}).`
            })
      env:
        URL: ${{ steps.ge.outputs.docs_url }}
        FAILED_CHECKPOINTS: ${{ steps.ge.outputs.failing_checkpoints }}
    
    # If a checkpoint succeeds, still comment.
    - name: Comment on PR upon Checkpoint success
      if: steps.ge.outputs.checkpoint_failure_flag == '0'
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Passed Great Expectations Checkpoint(s) \`${PASSED_CHECKPOINTS}\` detected for: ${process.env.GITHUB_SHA}.  Corresponding Data Docs have been generated and can be viewed [here](${process.env.URL}).`
            })
      env:
        URL: ${{ steps.ge.outputs.docs_url }}
        PASSED_CHECKPOINTS: ${{ steps.ge.outputs.passing_checkpoints }}
